#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

set -e

APP_HOME=$(cd "$(dirname "$0")" && pwd -P)

GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
GRADLE_WRAPPER_SHARED_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper-shared.jar"
GRADLE_WRAPPER_PROPERTIES="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"

if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
  echo "ERROR: gradle-wrapper.jar not found at $GRADLE_WRAPPER_JAR" >&2
  exit 1
fi

if [ ! -f "$GRADLE_WRAPPER_SHARED_JAR" ]; then
  echo "ERROR: gradle-wrapper-shared.jar not found at $GRADLE_WRAPPER_SHARED_JAR" >&2
  exit 1
fi

if [ -z "$JAVA_HOME" ]; then
  if command -v java >/dev/null 2>&1; then
    JAVA_CMD=java
  else
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found." >&2
    exit 1
  fi
else
  JAVA_CMD="$JAVA_HOME/bin/java"
fi

CLASSPATH="$GRADLE_WRAPPER_JAR:$GRADLE_WRAPPER_SHARED_JAR"
exec "$JAVA_CMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
