// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BootstrapGet() {
  return window['go']['main']['App']['BootstrapGet']();
}

export function BootstrapSet(arg1) {
  return window['go']['main']['App']['BootstrapSet'](arg1);
}

export function ClearAuth() {
  return window['go']['main']['App']['ClearAuth']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DequeueNotifications() {
  return window['go']['main']['App']['DequeueNotifications']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnsureKeys() {
  return window['go']['main']['App']['EnsureKeys']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MetricsSettingsGet() {
  return window['go']['main']['App']['MetricsSettingsGet']();
}

export function MetricsSettingsSet(arg1) {
  return window['go']['main']['App']['MetricsSettingsSet'](arg1);
}

export function NotifySettingsGet() {
  return window['go']['main']['App']['NotifySettingsGet']();
}

export function NotifySettingsSet(arg1) {
  return window['go']['main']['App']['NotifySettingsSet'](arg1);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function ShowNotification(arg1) {
  return window['go']['main']['App']['ShowNotification'](arg1);
}

export function StartNotify() {
  return window['go']['main']['App']['StartNotify']();
}

export function StartReporting() {
  return window['go']['main']['App']['StartReporting']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopNotify() {
  return window['go']['main']['App']['StopNotify']();
}

export function StopReporting() {
  return window['go']['main']['App']['StopReporting']();
}
