// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BootstrapGet() {
  return window['go']['main']['App']['BootstrapGet']();
}

export function BootstrapSet(arg1) {
  return window['go']['main']['App']['BootstrapSet'](arg1);
}

export function ClearAuth() {
  return window['go']['main']['App']['ClearAuth']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnsureKeys() {
  return window['go']['main']['App']['EnsureKeys']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function StartReporting() {
  return window['go']['main']['App']['StartReporting']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopReporting() {
  return window['go']['main']['App']['StopReporting']();
}
