// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {runtime} from '../models';

export function BootstrapGet():Promise<main.BootstrapDTO>;

export function BootstrapSet(arg1:main.BootstrapDTO):Promise<void>;

export function ClearAuth():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function EnsureKeys():Promise<string>;

export function Login(arg1:string,arg2:number):Promise<runtime.AuthSnapshot>;

export function MetricsSettingsGet():Promise<Array<runtime.MetricSetting>>;

export function MetricsSettingsSet(arg1:Array<runtime.MetricSetting>):Promise<void>;

export function Register(arg1:string):Promise<runtime.AuthSnapshot>;

export function StartReporting():Promise<void>;

export function Status():Promise<main.StatusDTO>;

export function StopReporting():Promise<void>;
